# This playbook deploys an OpenVas 20.08 scanner [Tested on a Debian 10 target machine]
- name: Deploy OpenVas on the target
  hosts: scanners
  vars_files:
    - vars/packages.yml

  pre_tasks:
    - name: Install required packages for OpenVas
      package:
        name:
          - "{{ item }}"
        state: present
      with_items:
        - "{{ packages_list }}"
  roles: 
    - role: openvas
 