# This playbook deploys an OpenVas 20.08 scanner [Tested on a Debian 10 target machine]
- hosts: scanners
  pre_tasks:
    - name: Install required packages for OpenVas
      package:
        name:
          - software-properties-common
          - cmake 
          - pkg-config
          - libglib2.0-dev
          - libgpgme-dev
          - libgnutls28-dev
          - uuid-dev 
          - libssh-gcrypt-dev
          - libldap2-dev
          - doxygen
          - graphviz
          - libradcli-dev
          - libhiredis-dev
          - libpcap-dev 
          - bison
          - libksba-dev 
          - libsnmp-dev
          - gcc-mingw-w64
          - heimdal-dev
          - libpopt-dev
          - xmltoman
          - redis-server
          - xsltproc
          - libical-dev
          - postgresql
          - postgresql-contrib
          - postgresql-server-dev-all
          - gnutls-bin
          - nmap
          - rpm
          - nsis
          - curl
          - wget
          - fakeroot
          - gnupg
          - sshpass
          - socat
          - snmp
          - smbclient
          - libmicrohttpd-dev
          - libxml2-dev
          - python-polib
          - gettext
          - rsync
          - xml-twig-tools
          - python3-paramiko
          - python3-lxml
          - python3-defusedxml
          - python3-pip
          - python3-psutil
          - virtualenv
          - vim
          - git
          - texlive-latex-extra
          - texlive-fonts-recommended
          - sudo
          - python-psycopg2
          - python3-psycopg2
          - yarnpkg
          - nodejs
        state: present
  roles: 
    - role: openvas
 